on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.NICHT_WICHTIG }}" | base64 -d > keystore.jks

      - name: Run code checks
        run: ./gradlew check

      - name: Upload ktlint reports
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-report
          path: app/build/reports/ktlint/

      - name: Build with Gradle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Clean up keystore
        if: always()
        run: rm -f keystore.jks
