on:
  schedule:
    - cron: '40 12 * * 5'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: DependencyCheck
      run: ./gradlew dependencyCheckAnalyze
